### ISSUE TITLE
[Vssue]简介 | EL-ADMIN 在线文档

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin-doc#58]
https://el-admin.vip/pages/010101/

**Comment by elunez** [comment]
1

**Comment by elunez** [comment]
测试

**Comment by elunez** [comment]
有问题可以评论

**Comment by Lion-Atom** [comment]
邮箱发送不出去，同时邮箱下的内容无法添加了

**Comment by Lion-Atom** [comment]
好的，谢谢您；我设置发邮件走了定时任务应该是我自身邮箱被封原因，富文本那边我尝试升级版本也是不行，您那边空了看看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elunez/eladmin-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [elunez/eladmin-doc] [Vssue]简介 | EL-ADMIN 在线文档 (Issue #58)





 
@Lion-Atom
  
邮箱发送不出去，同时邮箱下的内容无法添加了
  
邮件是可以正常发送的，出问题的是邮件下面的富文本编辑器，我有空了修复下
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elunez** [comment]
@Lion-Atom

> 好的，谢谢您；我设置发邮件走了定时任务应该是我自身邮箱被封原因，富文本那边我尝试升级版本也是不行，您那边空了看看
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "elunez/eladmin-doc"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年2月25日(星期五) 上午10:26
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [elunez/eladmin-doc] [Vssue]简介 | EL-ADMIN 在线文档 (Issue #58)
> 
> 
> 
> 
> 
>  
> @Lion-Atom
>   
> 邮箱发送不出去，同时邮箱下的内容无法添加了
>   
> 邮件是可以正常发送的，出问题的是邮件下面的富文本编辑器，我有空了修复下
>  
> 
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

富文本是升级了版本后配置发生改变导致的（把 editor.customConfig 改为 editor.config 即可），代码已经更新到 master 了

**Comment by Lion-Atom** [comment]
哈哈哈 我咋就没想到降板本试试，归根到底，没想着去看富文本的源码。。。谢谢您！
谢谢您这个EL-ADMIN，作为我进阶过程中的启蒙框架之一。
另外希望大大可以考虑以下建议：
1.文档类型的判定可适当添加大小写转换识别
2.可适当添加几例【watch】深度监控el-form下属性变化的案例
3.Springboot项目与vue项目整合打包，网上案例千奇百怪初学容易走很多弯路


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elunez/eladmin-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 上午10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [elunez/eladmin-doc] [Vssue]简介 | EL-ADMIN 在线文档 (Issue #58)





 
@Lion-Atom
  
好的，谢谢您；我设置发邮件走了定时任务应该是我自身邮箱被封原因，富文本那边我尝试升级版本也是不行，您那边空了看看
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "elunez/eladmin-doc"                                                                                    @.&gt;;
 发送时间:&nbsp;2022年2月25日(星期五) 上午10:26
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [elunez/eladmin-doc] [Vssue]简介 | EL-ADMIN 在线文档 (Issue #58)
 
@Lion-Atom
 
邮箱发送不出去，同时邮箱下的内容无法添加了
 
邮件是可以正常发送的，出问题的是邮件下面的富文本编辑器，我有空了修复下
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you were mentioned.Message ID: @.***&gt;
  
富文本是升级了版本后配置发生改变导致的（把 editor.customConfig 改为 editor.config 即可），代码已经更新到 master 了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elunez** [comment]
@elunez

> @Lion-Atom
> 
> > 邮箱发送不出去，同时邮箱下的内容无法添加了
> > 
> 
> 邮件是可以正常发送的，出问题的是邮件下面的富文本编辑器，富文本是升级了版本后配置发生改变导致不能显示
> 
> 把 editor.customConfig 改为 editor.config 就可以了，代码已经更新到 master 了
> 

测试

**Comment by alieliea** [comment]
后台登录页面的背景图，默认换下吧。。。。我们公司图省事没有改，结果被投诉了，说是日本的什么亭子，问我们想干嘛。。。。

**Comment by alieliea** [comment]
后台登录页面的背景图，默认换下吧（免得出现跟我们公司一样的尴尬情况）。。。。

我们公司图省事没有改背景图，结果被投诉了，说是日本的什么金阁寺，问我们想干嘛。。。。

**Comment by elunez** [comment]
@alieliea

> 后台登录页面的背景图，默认换下吧（免得出现跟我们公司一样的尴尬情况）。。。。
> 
> 我们公司图省事没有改背景图，结果被投诉了，说是日本的什么金阁寺，问我们想干嘛。。。。

收到，晚点修改下

**Comment by xukaixing** [comment]
webpack5.7，npm install提示 html-webpack-plugin错误，请帮忙回复如何解决，谢谢

**Comment by alieliea** [comment]
jpa查询一段sql，例如：select r.name,r.id,u.createtime from r left join u on u.r_id=r.id where u.code=xxxx
当使用for循环不同的code传入，执行jpa里的这段sql的时候，如果多次循环都出现相同的r.id返回值，则后续所有的u.createtime，都跟第一个相同的r.id的值里返回的u.createtime相同
r和u表的关系是一对多的
例如，循环code=[111,222,333,444]，循环返回的值：
code=111: r.id=1,r.name=1,u.createtime=2022-03-11
code=222: r.id=2,r.name=2,u.createtime=2022-03-12
code=333: r.id=3,r.name=3,u.createtime=2022-03-13
code=444: r.id=1,r.name=1,u.createtime=2022-03-11（这里的u表里实际值createtime=2022-03-14）

**Comment by ChunwaiLeung** [comment]
希望能出个mybatisplus版本的后端代码 那样受众应该会更广 会有更多人用到这么好的开源 star也会更高的

**Comment by alieliea** [comment]
前端页面meta.noCache值的设置，我新建的菜单，设置为true的时候，怎么都是无效的，state.cachedViews里面有值，但是切换回去的时候依旧是刷新页面
